---
- name: ensure systemd config
  template:
    src: template.service.j2
    dest: "/etc/systemd/system/docker.{{ container.name }}.service"
  loop_control:
    loop_var: container
  with_items:
    - "{{ docker_container }}"
  register: systemd_config
  notify:
    - reload systemctl

- name: ensure service is starting on bootup
  service:
    name: "docker.{{ container.name }}"
    state: "{{ container.state | default(docker_container_running_state) }}"
    enabled: "{{ container.enabled | default(docker_container_enabled) }}"
  loop_control:
    loop_var: container
  with_items:
    - "{{ docker_container }}"